"""initial_clean_schema

Revision ID: ab25714a0525
Revises: 
Create Date: 2026-05-06 18:17:20.746370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab25714a0525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('cashier_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_category', sa.Enum('MEAT', 'VEGETABLE', 'CHEESE', 'CANS', 'DRY', 'LEAVES', 'CONTAINERS', 'BREADS', 'MILKS', 'DISH_STUFF', 'UTILITY', 'STICKERS', name='item_category_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_category', sa.Enum('BREAKFAST', 'PIZZA', 'LUNCH_SANDWICH', 'GRAB_AND_GO_SANDWICH', 'SALAD', 'COFFEE', 'SIDE', 'BEVERAGE', name='menu_item_category_enum'), nullable=True),
    sa.Column('item_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('item_weight', sa.Float(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('item_price > 0', name='ck_item_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_items_category', 'menu_items', ['item_category'], unique=False)
    op.create_index(op.f('ix_menu_items_item_name'), 'menu_items', ['item_name'], unique=False)
    op.create_table('inventory_stock_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('stock_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'stock_date', name='unique_item_stock_per_day')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('daily_order_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('order_type', sa.Enum('DINE_IN', 'TAKE_AWAY', 'DELIVERY', name='ordertype'), nullable=False),
    sa.Column('totals', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_receipt_number'), 'orders', ['receipt_number'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_receipt_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('inventory_stock_history')
    op.drop_index(op.f('ix_menu_items_item_name'), table_name='menu_items')
    op.drop_index('ix_menu_items_category', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_table('inventory_items')
    op.drop_table('customer')
    # ### end Alembic commands ###
